IMPORT LIBRARIES

In [1]:
import numpy as np
import pandas as pd
import random
import os

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import *
from sklearn.naive_bayes import *
from sklearn.metrics import confusion_matrix, classification_report

print('Libraries imported.')

Libraries imported.


Setting up the environment

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


Importing the dataset through pandas

In [18]:
import json
filename = '/content/drive/My Drive/ML/noduplicatedataset.json'
db = pd.read_json(filename, lines=True)
print('File loaded: %d samples.\n\n' %(len(db.index)))

#print(db)
# Print a random item
print('%d %s %s' %(id,db.semantic[38],db.lista_asm[38]))

###
# From now on the elements of the json file can b accessed
# as they were attributes of the object db
# e.g. db.semantic[0] will return 'string'
# which is the semantic of the firt tuple of the json file
###

File loaded: 6073 samples.


513 string ['jmp qword ptr [rip + 0x202952]', 'push rbp', 'push r15', 'push r14', 'push rbx', 'push rax', 'mov ebp, ecx', 'mov r15d, edx', 'mov r14, rsi', 'mov rbx, rdi', 'test rbx, rbx', 'je 0xef', 'test r14, r14', 'je 0xd4', 'test r15d, r15d', 'js 0xcb', 'mov eax, dword ptr [rbx + 8]', 'cmp eax, ebp', 'jle 0xc2', 'test ebp, ebp', 'js 0xb7', 'cmp eax, r15d', 'jle 0xaf', 'sub ebp, r15d', 'jle 0x98', 'mov rdi, r14', 'call 0xffffffffffffed1e', 'inc ebp', 'cmp eax, ebp', 'cmovle ebp, eax', 'test ebp, ebp', 'jle 0x95', 'movsxd rbp, ebp', 'movsxd rcx, r15d', 'lea r8, [rbp - 1]', 'mov rdi, rbp', 'xor edx, edx', 'and rdi, 3', 'je 0x30', 'nop ', 'movzx eax, byte ptr [r14 + rdx]', 'mov rsi, qword ptr [rbx]', 'add rsi, rcx', 'mov byte ptr [rdx + rsi], al', 'inc rdx', 'cmp rdi, rdx', 'jne 2', 'movzx eax, byte ptr [r14 + rdx]', 'mov rsi, qword ptr [rbx]', 'add rsi, rcx', 'mov byte ptr [rdx + rsi], al', 'inc rdx', 'cmp rdi, rdx', 'jne 0', 'add rcx, rdx', 'cmp r8, 3', 'j

Compute vectorizer terms for all instances

In [4]:
# In this way we are able to manipulate the file as a vector of numbers

db.data = db.lista_asm
db.target = db.semantic

vectorizer = CountVectorizer() # multivariate

X_all = vectorizer.fit_transform(db.data)
y_all = db.target
print(vectorizer.get_feature_names())

print(X_all.shape)
print(y_all.shape)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  after removing the cwd from sys.path.


['0x10', '0x100', '0x1000', '0x10000', '0x100000000', '0x1001', '0x1004', '0x1005', '0x10056', '0x1007', '0x1008', '0x1009', '0x100c', '0x100c2', '0x100f', '0x101', '0x1010', '0x1011', '0x1013', '0x1014', '0x1015', '0x1016', '0x1017', '0x1018', '0x1019', '0x101a', '0x101c', '0x101d', '0x101f', '0x102', '0x1020', '0x1021', '0x1022', '0x1024', '0x1025', '0x1026', '0x1027', '0x1028', '0x1029', '0x102c', '0x102d', '0x102f', '0x103', '0x1030', '0x1031', '0x1032', '0x1033', '0x1034', '0x1035', '0x1036', '0x1038', '0x1039', '0x103a', '0x103b', '0x103c', '0x103f', '0x104', '0x1040', '0x1041', '0x1042', '0x104240', '0x104248', '0x104250', '0x104258', '0x104260', '0x104268', '0x10426c', '0x104270', '0x1044', '0x1046', '0x1047', '0x1048', '0x1049', '0x104a', '0x104b', '0x104c', '0x104f', '0x105', '0x1050', '0x1051', '0x1052', '0x1053', '0x1054', '0x1055', '0x1056', '0x1057', '0x1058', '0x105b', '0x105c', '0x105d', '0x105e', '0x106', '0x1060', '0x1061', '0x1062', '0x1064', '0x1068', '0x106a', '0x1

Split data

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X_all, y_all, 
          test_size=0.333, random_state=117)

print("Size of training set: %d" %X_train.shape[0])
print("Size of test set: %d" %X_test.shape[0])

Size of training set: 4050
Size of test set: 2023


Fit classifier

**Choose model to evaluate:**

In [6]:
from sklearn import tree
from sklearn import svm

classifier_name = 'S'

ClassifierMap = {
    'D':[tree.DecisionTreeClassifier],
    'S': [svm.LinearSVC, 'SVM']
    }

classifier = ClassifierMap[classifier_name][0]()

Fit the model

In [7]:
classifier.fit(X_train,y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
          intercept_scaling=1, loss='squared_hinge', max_iter=1000,
          multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
          verbose=0)

In [8]:
acc = classifier.score(X_test, y_test)    
print("Accuracy %.3f" %acc)

Accuracy 0.983


**Evaluation**

In [9]:
from sklearn.metrics import confusion_matrix, classification_report
y_pred = classifier.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print('\n')
print(classification_report(y_test, y_pred))

[[356   2   4   0]
 [  0 793   4   2]
 [  4   4 156   8]
 [  0   0   6 684]]


              precision    recall  f1-score   support

  encryption       0.99      0.98      0.99       362
        math       0.99      0.99      0.99       799
        sort       0.92      0.91      0.91       172
      string       0.99      0.99      0.99       690

    accuracy                           0.98      2023
   macro avg       0.97      0.97      0.97      2023
weighted avg       0.98      0.98      0.98      2023



**Prediction**

Import the blindset

In [10]:
# Importing the blindset

filename = '/content/drive/My Drive/ML/nodupblindtest.json'
bs = pd.read_json(filename, lines=True)
print('File loaded: %d samples.\n\n' %(len(db.index)))
print(bs)

File loaded: 6073 samples.


        id  ...                                                cfg
0    10351  ...  {'directed': True, 'graph': [], 'nodes': [{'id...
1    14513  ...  {'directed': True, 'graph': [], 'nodes': [{'id...
2     1767  ...  {'directed': True, 'graph': [], 'nodes': [{'id...
3     9384  ...  {'directed': True, 'graph': [], 'nodes': [{'id...
4     3018  ...  {'directed': True, 'graph': [], 'nodes': [{'id...
..     ...  ...                                                ...
616   9661  ...  {'directed': True, 'graph': [], 'nodes': [{'id...
617   6933  ...  {'directed': True, 'graph': [], 'nodes': [{'id...
618  11954  ...  {'directed': True, 'graph': [], 'nodes': [{'id...
619   5769  ...  {'directed': True, 'graph': [], 'nodes': [{'id...
620   7957  ...  {'directed': True, 'graph': [], 'nodes': [{'id...

[621 rows x 3 columns]


Compute vectorizer terms again and do prediction over the new unlabeled set



In [11]:
# In this way we are able to manipulate the file as a vector of numbers

i=13
item = np.array(list(bs.lista_asm))
new_x = vectorizer.transform(item)
new_y = classifier.predict(new_x)

#print('%s %s' %(item,new_y))

Show a random sample and print output onto a txt file

In [17]:


id = random.randrange(0,len(new_y))
print('%d %s %s' %(id,new_y[id],bs.lista_asm[id]))

f = open('1894954.txt',mode='w+')

for item in new_y:
  f.write(item + '\n')

f.close()

513 math ['ucomisd xmm0, xmm0', 'jp 0x50', 'sub rsp, 0x38', 'mov edx, 1', 'mov esi, 1', 'lea rcx, [rsp + 0x20]', 'lea r9, [rsp + 0x10]', 'mov r8, rsp', 'mov edi, 1', 'call 0x25', 'mov eax, dword ptr [rsp + 0x10]', 'movsd xmm0, qword ptr [rsp + 0x20]', 'test eax, eax', 'je 0x21', 'ret ']
